name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show file list
        run: ls -la

      - name: Run a simple check
        run: |
          test -f hello.txt
          echo "All good ✅"
